version: '3.8' # Version du format Docker Compose

services:
  db:
    # Utilisation de l'image MariaDB (compatible Raspberry Pi et Windows)
    image: mariadb:10.6
    container_name: mysql_poubelles
    restart: always # Redémarre automatiquement si le Raspberry s'éteint

    # Configuration des variables d'environnement (Identifiants)
    environment:
      MYSQL_ROOT_PASSWORD: root        # Mot de passe administrateur
      MYSQL_DATABASE: smart_bins      # Nom de la base créé au démarrage
      MYSQL_USER: web_user            # Utilisateur pour l'Étudiant 3 (Site Web)
      MYSQL_PASSWORD: poubelle2026    # Mot de passe de l'utilisateur web

    # Liaison des ports : "Port_PC : Port_Conteneur"
    ports:
      - "3306:3306"

    # Synchronisation des fichiers (L'étape la plus importante)
    volumes:
      # 1. On envoie ton script de création des tables
      - ./install.sql:/docker-entrypoint-initdb.d/1_install.sql
      # 2. On envoie ton script de données de test
      - ./test_data.sql:/docker-entrypoint-initdb.d/2_test_data.sql
      # 3. On crée un dossier local pour stocker les données réellement
      # Cela évite de perdre tes données si tu supprimes le conteneur
      - ./db_data:/var/lib/mysql

networks:
  default:
    name: smart_bins_network