# ============================================
# Configuration Apache SSL - Smart Trash
# ============================================

<VirtualHost *:443>
    DocumentRoot /var/www/html

    SSLEngine on
    SSLCertificateFile    /etc/ssl/certs/smart-trash.crt
    SSLCertificateKeyFile /etc/ssl/private/smart-trash.key

    <Directory /var/www/html>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# Redirection HTTP → HTTPS
<VirtualHost *:80>
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}:8443$1 [R=301,L]
</VirtualHost>